
language: go

go:
  - "1.13"
  - tip

install:
  - go get -t ./...

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go build -o go-cli-simple-cobra main.go
  - ./go-cli-simple-cobra add 1 2

after_success:
  - bash <(curl -s https://codecov.io/bash)